server:
  port: 8078
  servlet:
    context-path: /assignment-service

spring:
  application:
    name: assignment-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=true
    username: client
    password: client@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.nna.assignment: DEBUG
  file:
    name: logs/api.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
